server:
  port: 8080
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pethome?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
  mail:
    host: smtp.qq.com
    port: 465
    username: 1873270473@qq.com
    password: ripjlupkqzxebjjc
    default-encoding: UTF-8
    properties:
      mail:
            SMTP:
              auth: true
              STARTTLS:
                enable: false  # 465端口不需要starttls
              ssl:
                enable: true  # 必须为true
                required: true
            transport:
              protocol: SMTP
            debug: true  # 查看详细日志

# MyBatis 配置
mybatis:
  # mapper XML 文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类的别名包
  type-aliases-package: com.kingbo.petserver.entity
  configuration:
    # 开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    # 允许 JDBC 支持自动生成主键，需要数据库驱动支持
    use-generated-keys: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true

aly:
  endPoint: https://oss-cn-hangzhou.aliyuncs.com
  bucket: kingbo111
  sceneList: porn,terrorism,ad,live,logo
  labelList: spam,politics,abuse,terrorism,porn,flood,contraband,ad


debug: true

token:
  secret: 12345678901234567890123456789012

jwt:
  key: bilghsifduhaouihfowhfoeehdsfiuaphewrfpihdsuif
  hm: 60000000
